# Generated by Django 4.0.3 on 2022-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_login', models.EmailField(max_length=250)),
                ('use_password', models.CharField(max_length=128)),
                ('use_status', models.SmallIntegerField(default=0)),
                ('use_date_created', models.DateTimeField(auto_now_add=True)),
                ('use_date_updated', models.DateTimeField(auto_now=True)),
                ('use_date_deleted', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
