# Generated by Django 4.0.3 on 2022-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='use_status',
            field=models.BooleanField(default=False),
        ),
    ]
