# Generated by Django 4.0.3 on 2022-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_users_use_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
