# Generated by Django 4.0.3 on 2022-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_users_user_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_updated',
            field=models.DateTimeField(),
        ),
    ]
