# Generated by Django 4.0.3 on 2022-03-28 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_options_alter_user_use_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 13, 41, 56, 677684)),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 13, 41, 56, 677707)),
        ),
    ]
