# Generated by Django 4.0.3 on 2022-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_use_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
