# Generated by Django 4.0.3 on 2022-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_use_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_date_updated',
            field=models.DateTimeField(),
        ),
    ]
