# Generated by Django 4.0.3 on 2022-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_use_is_valid_alter_user_use_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
