# Generated by Django 4.0.3 on 2022-04-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_use_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_user_agent', models.CharField(max_length=250)),
                ('log_ip_address', models.CharField(max_length=250)),
                ('log_ip_type', models.CharField(max_length=4)),
                ('log_ip_country', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('log_ip_country_flag', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('log_ip_region', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('log_ip_city', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('log_ip_latitude', models.DecimalField(blank=True, decimal_places=9, default=None, max_digits=12, null=True)),
                ('log_ip_longitude', models.DecimalField(blank=True, decimal_places=9, default=None, max_digits=12, null=True)),
                ('log_location', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('log_action', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('log_method', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('log_risk_level', models.SmallIntegerField()),
                ('log_risk_comment', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('log_date_created', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
    ]
