# Generated by Django 4.0.3 on 2022-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_risk_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
