# Generated by Django 4.0.3 on 2022-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userlog_log_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_ip_type',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
