# Generated by Django 4.0.3 on 2022-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_userlog_log_ip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='log_action',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='log_location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
