# Generated by Django 4.0.3 on 2022-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_userlog_log_action_alter_userlog_log_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_method',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
