# Generated by Django 4.0.3 on 2022-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userlog_log_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='log_method',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
