# Generated by Django 4.0.3 on 2022-04-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_ben_date_created_beneficiarycategory_cat_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_description',
            new_name='ben_name',
        ),
    ]
