# Generated by Django 4.0.3 on 2022-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_beneficiary_ben_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='ben_slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
