# Generated by Django 4.0.3 on 2022-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_beneficiary_ben_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarycategory',
            name='cat_slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
