# Generated by Django 4.0.3 on 2022-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.SmallIntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
