# Generated by Django 4.0.3 on 2022-04-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_category_cat_type_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_category',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='board.beneficiarycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='board.category'),
            preserve_default=False,
        ),
    ]
