# Generated by Django 4.0.3 on 2022-05-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cli_email',
            field=models.EmailField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
