# Generated by Django 4.0.3 on 2022-05-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_userlog_log_location_alter_userlog_log_method'),
        ('board', '0014_alter_client_cli_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
    ]
