# Generated by Django 4.0.3 on 2022-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cli_slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
