# Generated by Django 4.0.3 on 2022-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_country_cou_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cou_image',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
