# Generated by Django 4.0.3 on 2022-05-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_userlog_log_location_alter_userlog_log_method'),
        ('board', '0019_country_cou_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_slug', models.SlugField(max_length=250, unique=True)),
                ('fin_cost_center', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('fin_description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('fin_bank_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('fin_bank_branch', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('fin_bank_account', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('fin_type', models.SmallIntegerField()),
                ('fin_status', models.BooleanField(default=False)),
                ('fin_date_created', models.DateTimeField(editable=False)),
                ('fin_date_updated', models.DateTimeField()),
                ('fin_date_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
