# Generated by Django 4.0.3 on 2022-05-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_userlog_log_location_alter_userlog_log_method'),
        ('board', '0020_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_slug', models.SlugField(max_length=250, unique=True)),
                ('rel_gen_status', models.SmallIntegerField()),
                ('rel_entry_date', models.DateField()),
                ('rel_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rel_monthly_balance', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rel_overall_balance', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rel_description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('rel_sqn', models.IntegerField()),
                ('rel_status', models.BooleanField(default=False)),
                ('rel_date_created', models.DateTimeField(editable=False)),
                ('rel_date_updated', models.DateTimeField()),
                ('rel_date_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.beneficiary')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.client')),
                ('financial_account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_account', to='board.financial')),
                ('financial_cost_center', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_cost_center', to='board.financial')),
                ('subcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_cycle', models.DateField()),
                ('ana_json', models.TextField()),
                ('ana_status', models.BooleanField(default=False)),
                ('ana_date_created', models.DateTimeField(editable=False)),
                ('ana_date_updated', models.DateTimeField()),
                ('ana_date_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
